- name: Create nodeusr group
  group:
    name: nodeusr
    state: present

- name: Create nodeusr user
  user:
    name: nodeusr
    shell: /bin/false
    createhome: no
    groups: nodeusr

- name: Download And Unzipped Node Exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp
    creates: /tmp/node_exporter-1.5.0.linux-amd64
    remote_src: yes

- name: Copy Bin Files From Node Exporter
  copy:
    src: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin 
    mode: 0755
    owner: nodeusr
    group: nodeusr
    remote_src: yes

- name: Render Node Exporter service template
  ansible.builtin.template:
    src: node_exp_service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Service enable
  ansible.builtin.systemd:
    state: started
    name: node_exporter
    daemon_reload: true
    enabled: true
  