---
- name: Create Prometheus user
  user:
    name: prometheus
    shell: /bin/false
    createhome: no
    groups: prometheus

- name: Create Prometheus group
  group:
    name: prometheus
    state: present

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download And Unzipped Prometheus 
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
    dest: /tmp/prometheus 
    creates: /tmp/prometheus/prometheus-2.46.0.linux-amd6
    remote_src: yes 

- name: Copy Bin Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-2.46.0.linux-amd6{{ item }}
    dest: /usr/local/bin 
    mode: 0755
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]

- name: Copy Conf Files From Unzipped to Prometheus 
  copy:
    src: /tmp/prometheus/prometheus-2.46.0.linux-amd6{{ item }}
    dest: /etc/prometheus 
    mode: 0755
    owner: prometheus
    group: prometheus
  loop: [ 'console_libraries', 'consoles', 'prometheus.yml' ]
