---
# tasks file for monitoring
- include_tasks: 
    file: install_prom.yml
    apply:
      tags: install_prom
  tags: [ install_prom, never ]

- include_tasks: 
    file: prom_cfg.yml
    apply:
      tags: srv_prom_cfg
  tags: [ srv_prom_cfg, never ]

