- name: Add Prometheus Data Source
  grafana_datasource:
    name: Prometheus
    ds_type: prometheus
    ds_url: http://monitoring:9090
    url: http://monitoring:3000
    tls_skip_verify: true

- name: Import Grafana dashboard prometheus
  community.grafana.grafana_dashboard:
    grafana_url: http://monitoring:3000
    dashboard_id: 1860