---
- name: Fetch MongoDB config file
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Fetch grafana file
      ansible.builtin.fetch:
        src: "/etc/grafana/grafana.ini"
        dest: "./grafana.ini"
        flat: yes