---
- name: Fetch MongoDB config file
  hosts: backend1
  gather_facts: true

  tasks:
    - name: Fetch rsyslog config file
      ansible.builtin.fetch:
        src: "/etc/rsyslog.conf"
        dest: "./rsyslog.j2"
        flat: yes