
- name: Create directory for Node.js app
  ansible.builtin.file:
        path: /var/node/sports-helper
        state: directory
        owner: node
        group: node

- name: Synchronize local folder contents to remote server
  ansible.builtin.synchronize:
      src: ../server/
      dest: /var/node/sports-helper/
      recursive: yes
      delete: yes

- name: Install packages based on package.json.
  community.general.npm:
    path: /var/node/sports-helper