---
# tasks file
- include_tasks: 
    file: install_node.yml
    apply:
      tags: install_node
  tags: [ install_node, never ]

- include_tasks: 
    file: create.yml
    apply:
      tags: create
  tags: [ create, never ]

- include_tasks: 
    file: copy_app.yml
    apply:
      tags: copy_app
  tags: [ copy_app, never ]