- name: Fix add arbitr to mongo
  shell: |
       mongo -u "{{ mongodb_root_user }}" -p {{ mongodb_root_password }} --eval 'db.adminCommand({"setDefaultRWConcern": 1, "defaultWriteConcern": {"w": 1}})'
  when: inventory_hostname == "backend1"

- name: Create file to initiate replica set
  template: 
    src: replSetInit.j2
    dest: ./replSetInit.js
  when: inventory_hostname == "backend1"

- name: Initialize the replica set
  command: mongo -u "{{ mongodb_root_user }}" -p {{ mongodb_root_password }} ./replSetInit.js
  when: inventory_hostname == "backend1"