

- name: Configure primary MongoDB node
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongodb_root_user }}"
    login_password: "{{ mongodb_root_password }}"
    replica_set: "{{ replicaSetName }}"
    members:
      - "{{ mongo_primary }}:27017"
      - "{{ mongo_secondary }}:27017"
    validate: no
  when: inventory_hostname == "backend1"

- name: Configure secondary MongoDB node
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongodb_root_user }}"
    login_password: "{{ mongodb_root_password }}"
    replica_set: "{{ replicaSetName }}"
    members:
      - "{{ mongo_primary }}:27017"
      - "{{ mongo_secondary}}:27017"
    validate: no
  when: inventory_hostname == "backend2"