- name: create MongoDB repository file
  ansible.builtin.template:
    src: mongodb-org.repo.j2
    dest: /etc/yum.repos.d/mongodb-org-3.6.repo

- name: Install MongoDB packages
  ansible.builtin.yum:
     name:
       - mongodb-org
       - mongodb-org-server
       - mongodb-org-shell
       - mongodb-org-mongos
       - mongodb-org-tools
  
- name: Добавить запись в /etc/hosts
  lineinfile:
     path: /etc/hosts
     line: '127.0.0.1 mongo'

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: mongod
    daemon_reload: true
    enabled: true