- name: Make HTTPS GET request
  uri:
     url: "{{ item }}"
     method: GET
     validate_certs: no
  loop:
     - "{{ site_name }}"
     - "{{ site_name }}/users"
  register: http_results

- name: Display HTTP response details
  debug:
    var: item
  loop: "{{ http_results.results }}"