---
# tasks file for VM_WIREGUARD
- include_tasks: 
    file: install_nginx.yml
    apply:
      tags: install_nginx
  tags: [ install_nginx, never ]

- include_tasks:
    file: syn_fold.yml
    apply:
      tags: syn_fold
  tags: [ syn_fold, never ]
