# task  for syn fold
- name: mkdir for web
  file:
    path: "/var/www/sports-helper"
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Copy client files to /var/www/sports-helper
  synchronize:
    src: "../../client/build/"
    dest: "/var/www/sports-helper"
    delete: yes

#права на папки 0755 а на файлы 0644 так как umsask 0022
- name: Set ownership and permissions for nginx user
  file:
    path: "/var/www/{{ frontend_name }}"
    owner: nginx
    group: nginx
    recurse: yes
  
  notify:
     - Restart Nginx
