# task  for syn fold
- name: mkdir for web
  file:
    path: "/var/www/sports-helper"
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"
  become: true

- name: Copy client files to /var/www/sports-helper
  synchronize:
    src: "../../client/build"
    dest: "/var/www/sports-helper"
    delete: yes

- name: Set ownership and permissions for www user
  file:
    path: "/var/www/{{ frontend_name }}"
    owner: nginx
    group: nginx
    mode: "0755"
    become: true

  notify:
     - Restart Nginx
