- name: create certs
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.57.2 sports-helper"
        - "192.168.57.2 frontend"
        - "192.168.57.3 backend1"
        - "192.168.57.4 backend2"
        - "192.168.57.5 backup"