- name: Ensure firewalld is installed
  yum:
     name: firewalld
     state: present

- name: Start and enable firewalld
  service:
     name: firewalld
     state: started
     enabled: yes

- name: Open TCP ports in the firewall
  firewalld:
     port: "{{ item }}/tcp"
     permanent: yes
     state: enabled
     immediate: yes
  loop: "{{ allow_ports }}"